### ISSUE TITLE
I have finished the challenge1,2,3，but i didn't get the reward.

### ISSUE THREAD

**Issue by halw001** [ovrclk/ecosystem#662]
MY Participation Code"1w3hg0t5tybalkp" is on the list but the rewards are 0.
my PR link:https://github.com/ovrclk/ecosystem/pull/422
my commit time was before the deadline

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We found another PR: #513 with all week1 challenges' commit time changed. That's the reason, rewards are 0. We will update rewards for you based on PR: #422

**Comment by halw001** [comment]
> Thanks for reporting. We found another PR: #513 with all week1 challenges' commit time changed. That's the reason, rewards are 0. We will update rewards for you based on PR: #422

thanks
