### ISSUE TITLE
Rewards for Challenge 1 and Bonus Rewards - Week 1

### ISSUE THREAD

**Issue by daluxxx** [ovrclk/ecosystem#663]
Dear ladies and gentlemen,

First of all, I want to say thank you for the great opportunity and the awesome challenges that you set up within the last weeks. It was a huge learning experience for me and a good opportunity to get to know Akash better. Also thank you to the team who did a good preparation and a good support before and during the challenges.

Regarding my issue:

I participated in all 6 challenges and I also did challenge 1-3 in time. I also got the reward points for challenge 2 and 3. However, for challenge 1 I did not receive the points. However, from my point of view I did the challenge 1 in time and also uploaded it in time to github.

The only reason I could imagine why I did not receive the points is, because my PR was labelled first as kind/invalid because the directory where I uploaded the PR in github did not match. But after I saw the comment, I immediately changed the directories and this was also before the end of the challenge. Nevertheless, I also think that it would be not that fair if I would not get the points, just because the upload directory was in the first place was not correct, as the challenge itself was completed (and it was only related to the github folder). After changing the directory in github, I also confirmed it with one of your team members in Discord to be correct.

I hope you could revise my points for challenge 1 again and after that also the calculation of the bonus rewards as I did the challenge 1 really fast and also uploaded it timely.

My data is:

Participation code: 2rr43jcvrwpoqfg

Please let me know, if you need anything else. Looking forward to your feedback.

Thank you in advance
daluxxx

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We took the commit time of your challenge-1 file when it is moved to correct directory. And that commit time is after the challenge-1 deadline time. That's the reason, you were not rewarded for challenge-1. We will update your rewards by taking first submit time of challenge-1.
