### ISSUE TITLE
please check my pull request once again

### ISSUE THREAD

**Issue by djpcclubb** [ovrclk/ecosystem#664]
https://github.com/ovrclk/ecosystem/pull/243
I completed all tasks on time, but I don't see rewards for Challenge3 and Week1 Bonus Rewards
Can you check and explain what's wrong?

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/commit/cfc2080e6daa5cb3371a443392f913e9b4b53295#diff-6cbdac446f0424b55fac3fb827e56caa60d5e5934eff46b1cff157f5e3085fdf) for challenge-3. As commit  time of it is before challenge start time, we took it as  invalid. We will revise your rewards based on updated challenge-3 json.
