### ISSUE TITLE
phase 3 challenges 

### ISSUE THREAD

**Issue by alixsun0215** [ovrclk/ecosystem#665]
when I made pr,I submitted the json by 'PARTICIPANT_CODE' by mistake.LoL.

**Comment by alixsun0215** [comment]
'PARTICIPATE_CODE' lol.I am not a English native.

**Comment by alixsun0215** [comment]
![Uploading 微信图片_20201217103021.jpg…]()

**Comment by alixsun0215** [comment]
![微信图片_20201217103021](https://user-images.githubusercontent.com/26176928/102436206-07aa5a00-4053-11eb-85f0-7bb50423676a.jpg)

**Comment by alixsun0215** [comment]
You can visit https://github.com/ovrclk/ecosystem/pull/397/commits to check my commits.take the first commit challenge1 as a example.Screenshot belows.
![微信图片_20201217105914](https://user-images.githubusercontent.com/26176928/102438285-f06d6b80-4056-11eb-9e31-051bfdf309d0.png)

**Comment by akhilkumarpilli** [comment]
Can you share us your participation code. We can update it in leaderboard.

**Comment by alixsun0215** [comment]
hi, it is
6dw9cork0utkmmo  ,thank u
| |
17665226448
|
|
15572118812@163.com
|
签名由网易邮箱大师定制
On 12/17/2020 13:41，Akhil Kumar P<notifications@github.com> wrote：

Can you share us your participation code. We can update it in leaderboard.

**Comment by akhilkumarpilli** [comment]
Thank you @alixsun0215. We will update it. We are closing this issue now.
