### ISSUE TITLE
week1 chanllenge3

### ISSUE THREAD

**Issue by damon-pk** [ovrclk/ecosystem#666]
#336
I got week1 chanllenge1 and chanllenge2 rewards, but chanllenge3 reward is 0,I'm sure I made the PR in time and within the max limit,I  don't know where is wrong, please check it. 
thank you very much.

**Comment by akhilkumarpilli** [comment]
We found commit time of your challenge-3 file is before the challenge-3 start time. That's the reason, your challenge-3 reward is 0. Thank you.

**Comment by damon-pk** [comment]
I see, Thank you very much
