### ISSUE TITLE
week1 chanllenge3 rewards

### ISSUE THREAD

**Issue by catgromon** [ovrclk/ecosystem#667]
Hello,

My  #244, but no rewards for chanllenge3. Please look into issue

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/commit/aa96388c0a3a5af51743ebdcb55b5b99627c6b79) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
