### ISSUE TITLE
chanllenge3 issue

### ISSUE THREAD

**Issue by valerchegs** [ovrclk/ecosystem#668]
I completed this stage successfully, but I don't see the result in the table. Please check up

**Comment by akhilkumarpilli** [comment]
Can you share me your participation code and PR numbers of your challenges.

**Comment by valerchegs** [comment]
#214 4qoosuxone3zd6t

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. Result for `ID: 4qoosuxone3zd6t` is present in table. But, we mistakenly considered [this file](https://github.com/ovrclk/ecosystem/blob/918169945e0dc3152926c53ae0172429047b02b8/akashian/phase3/challenge3/4qoosuxone3zd6t.json) for challenge-3. As commit time of it is before challenge start time, we took it as invalid for challenge-3. We will revise your rewards based on updated challenge-3 json.
