### ISSUE TITLE
Please check my PR #218

### ISSUE THREAD

**Issue by animaross** [ovrclk/ecosystem#669]
Please check my PR #218, i don't see rewards for Challenge 3

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/blob/b7371ad04cae35d1643acf8b8edd280ef2ce510e/akashian/phase3/challenge3/ekrnp4qmgkizhvw.json) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
