### ISSUE TITLE
week 1 chalenge 3 rewards prob

### ISSUE THREAD

**Issue by waccomte** [ovrclk/ecosystem#670]
My PR #224 please look into issue

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/pull/224/commits/4d9221519bc95a1a3c9061dc90337a1a4cac3212) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
