### ISSUE TITLE
Validator up since the beginning of edgetnet but late PR

### ISSUE THREAD

**Issue by jetlag666** [ovrclk/ecosystem#672]
Hello, my validator called "jetlife" has been up since the beginning of the edgenet testnet but I did the PR for it a bit late because I didn't know that you had to make one for validators rewards. 

The PR is here https://github.com/ovrclk/net/pull/401 and the validator address was akashvaloper10cwmzwvkfcvmtj5egexqvcgcpardg3aurzumgc

Thanks, in advance.

**Comment by akhilkumarpilli** [comment]
Sorry, as PRs are the only way to calculate RPC, API rewards, we can't reward you RPC, API rewards.

Coming to validator rewards, 50 validators will be rewarded with uptime and created time as priority. Taking them into consideration, your validator didn't make into top 50 validators list. That's the reason, your validator is not shown in validator rewards table.
