### ISSUE TITLE
Not shown in Network RPC, API Rewards

### ISSUE THREAD

**Issue by daluxxx** [ovrclk/ecosystem#673]
Dead ladies and gentlemen,

Thank you for publishing the challenge rewards. I had a look at it and I am not showing up on the Network RPC, API Rewards, however, my validator ran the whole 2 weeks and I also had the RPC and API interface open.

My particiation code is: "2rr43jcvrwpoqfg"
RPC Address: "tcp://185.232.68.12:26657"
API Address: "http://185.232.68.12:1317"

Could you please check that?

Thank you in advance
daluxx

**Comment by akhilkumarpilli** [comment]
Sorry, we can't find any PR with RPC, API details for given participation code. We are considering early 50 PRs with RPC, API details for RPC, API rewards as we don't have any other alternative way to calculate them.

**Comment by daluxxx** [comment]
Dear Akhil,Where was it stated that we have to add a PR for API and RPC rewards? That’s new to me and I cannot find that on https://akash.network/challenge/Am 22.12.20 um 06:27 schrieb Akhil Kumar P
                
            
            
                
                    Von: "Akhil Kumar P" <notifications@github.com>Datum: 22. Dezember 2020An: "ovrclk/ecosystem" <ecosystem@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"daluxxx" <hidde@alphafrau.de>Betreff: Re: [ovrclk/ecosystem] Not shown in Network RPC, API Rewards (#673)
                
                
Sorry, we can't find any PR with RPC, API details for given participation code. We are considering early 50 PRs with RPC, API details for RPC, API rewards as we don't have any other alternative way to calculate them.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ovrclk/ecosystem/issues/673#issuecomment-749346872",
"url": "https://github.com/ovrclk/ecosystem/issues/673#issuecomment-749346872",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by boz** [comment]
@daluxxx, the instructions are pretty clear on this: https://docs.akash.network/testnet-challenges/testnet-challenges/network-support#submission

I'm sorry that we can't accommodate you - it would be unfair to the participants that followed all of the rules
