### ISSUE TITLE
Not shown in rewards table

### ISSUE THREAD

**Issue by Anonstake** [ovrclk/ecosystem#674]
Hello!

I am running a validator node since 2nd of December with rpc, api & lcd port open. Here is my PR: https://github.com/ovrclk/net/pull/332

I can't find my validator & node among the Week 2 or network validator/rpc&api results. Could someone please check why?

Info:
http://159.69.89.235:1317
tcp://159.69.89.235:26657
3041e3cd0c4d603418a17a22fed8b75afac2b85d@159.69.89.235:26656
Validator Anonstake
Code: 40w3pny1qc0e6dk

Thanks in advance!

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. Sorry, we missed your PR as it is merged. We will try to revise your RPC, API rewards. 

Coming to validator rewards, 50 validators will be rewarded with uptime and created time as priority. Taking them into consideration, your validator didn't make into top 50 validators list. That's the reason, your validator is not shown in validator rewards table.

**Comment by akhilkumarpilli** [comment]
After checking again, we found that your PR for RPC, API rewards is bit late and didn't make into early 50 PRs. So, that's the reason, your validator is not found in RPC, API rewards table.

Coming to validator rewards, 50 validators will be rewarded with uptime and created time as priority. Taking them into consideration, your validator didn't make into top 50 validators list. That's the reason, your validator is not shown in validator rewards table.

**Comment by Anonstake** [comment]
Thank you for the explanation. Based on my PR, I should still receive rewards for Week 2 - for setting up validator/ rpc / api?

**Comment by akhilkumarpilli** [comment]
Sorry, week-2 rewards are for completing guided deployment challenges. And for setting up validator, we have network rewards separately i.e., validator and rpc-api rewards.
