### ISSUE TITLE
validator rpc/api

### ISSUE THREAD

**Issue by iunna-web** [ovrclk/ecosystem#676]
Good day. my account for participation in akash was flagged in github was flagged 
http://prntscr.com/w7ore6
my PR is 304
my id 1rzr5x4dyeu0y5t

**Comment by akhilkumarpilli** [comment]
For RPC, API nodes, we can consider only the publicly available PRs. If your PRs are flagged, others cannot use your rpc or api address for deploying apps. So it cannot come under reward criteria. Thank you.
