### ISSUE TITLE
Please verify my PR (Challenge4/6)

### ISSUE THREAD

**Issue by activenodes** [ovrclk/ecosystem#677]
Hi Guys, I followed the Team in "quality control" of the documentation for the challenges and helped the Discord community during the times of the challenges.
Strange that it didn't get point for:
- Challenge4
- Challenge6
- Week2 Bonus Rewards

Please check my PR: https://github.com/ovrclk/ecosystem/pull/217/files

Thank you so much
Simo|AC

**Comment by akhilkumarpilli** [comment]
@simvirus , Thanks for reporting. We will check once again and give you rewards. And thanks a lot for your efforts in helping Discord Community.
