### ISSUE TITLE
PR 245 and challenge 3 points

### ISSUE THREAD

**Issue by clevrfrog** [ovrclk/ecosystem#678]
Hi, my PR 245, please verify my challenge 3
Thx

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/pull/245/commits/24f7451985ffa2e9020db202daf74eaaa7754060) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
