### ISSUE TITLE
Challenge 3 rewards

### ISSUE THREAD

**Issue by headroomst** [ovrclk/ecosystem#679]
I don't see points in leadeebord for challenge 3
https://github.com/ovrclk/ecosystem/pull/206
could you please check it?

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/pull/206/commits/aa07ca1d6df6c8740e21803453ff5266af880d19) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
