### ISSUE TITLE
3 Challenge #239

### ISSUE THREAD

**Issue by kerinovabit** [ovrclk/ecosystem#680]
Dear Sirs,

My PR number #239. I checked, everything looks good, but the challenge does not count, please check again.

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/pull/239/commits/09159c89fcaab492796ae96bdf749b0f012b4be6) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
