### ISSUE TITLE
 About the reward list for Challenge 3

### ISSUE THREAD

**Issue by yAntPower** [ovrclk/ecosystem#681]
I participated in Challenge 3 and successfully submitted the documents, but I did not see my information in the award list.
This is my submission record https://github.com/yAntPower/ecosystem/commit/14e4c0491278cee0dd3fbe8984ad6121206e807c

**Comment by akhilkumarpilli** [comment]
@yAntPower , we can't find any PRs to `ovrclk/ecosystem` with your participation code: `54r8be7k8ssndxp`. Sorry, we cannot accommodate you rewards. Thank you.
