### ISSUE TITLE
I don't see the result in the table for the Challenge 3

### ISSUE THREAD

**Issue by hitexmax** [ovrclk/ecosystem#682]
Hello, my PR https://github.com/ovrclk/ecosystem/pull/241
Please review.

**Comment by akhilkumarpilli** [comment]
Thanks for reporting. We mistakenly considered [this file](https://github.com/ovrclk/ecosystem/pull/241/commits/165c22cf4fd03460db9d3111bb33949953078fd6) for challenge-3. As commit time of it is before challenge start time, we took it as invalid. We will revise your rewards based on updated challenge-3 json.
