### ISSUE TITLE
Validator & RPC, API Rewards potentially missing

### ISSUE THREAD

**Issue by Chainode** [ovrclk/ecosystem#683]
Hi guys!

I have a couple of questions:

- I can't find the data for my validator rewards: 
ID: 3biwy2ymjnknb
IP: 62.171.135.251

- For RPC,API Rewards my ID was on the list but I checked now and it has been removed?
Link to my PR: https://github.com/ovrclk/net/pull/328 The PR is definitely within first 50 submitted. 
As for the uptime of the validator I would be curious to see the data as the 80% shouldn't have been an issue.

Best for these kind of competitions would be to simply share the data you are using so that we can also check ourselves the metrics. 

Thanks!

**Comment by akhilkumarpilli** [comment]
Hello @Chainode , The reason for removing your ID from rpc rewards list is, we didn't check some PRs which were merged and those PRs are created earlier than your PR. After considering them, your PR didn't make into first 50 PRs list. 

And coming to validator rewards, your validator has 88% uptime but your validator is created bit late compared to first 50 validators. We are considering validators with uptime above 80% ordered by created time.

We will discuss with team and will try to show all relevant data we are using for rewards. Thank you.

**Comment by Chainode** [comment]
Ok, thank you for the info.
